# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe70d5510dfa19c2346ec6e64d6d46c99b33d20b39ff8598427a42ce16bbfbae498f71460c86326836a9beb0491d77108c94f76142d4f5311b3a67cd386a8f9a

test:
  secret_key_base: 20bce464884e6fc96eb2ade83335b4e81bed592a843138f618815c604c3d588d2ffb7ab2ac8a3557c2af366bea1e048b8d92016bc3ce702e070fbb77d4b53c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
